name: ci/cd
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  buildAndDeploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Npm clean, install, build, and test
        run: | 
          npm ci
          npm run build
          npm run test:ci

      - name: 'Deploy to Azure'
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'project-twitter-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.WEB_APP_PUBLISH_PROFILE }}
          package: .
  